plugins {
    id 'com.android.application'
}

android {
    namespace 'com.alkhalijialawal.k1employee.v2'
    compileSdk 35

    defaultConfig {
        applicationId "com.alkhalijialawal.k1employee.v2"
        minSdk 23
        targetSdk 35
        versionCode 20000
        versionName "2.0.0"
    }
}
