name: Temporary APK Runner
on:
  push:
    branches:
      - apk-builder-runner-test
      - sales-assistant-apk-build
jobs:
  test:
    if: github.ref_name == 'apk-builder-runner-test'
    runs-on: ubuntu-latest
    steps:
      - run: echo "runner works"
